app/routes/routesLogin.py
from flask import Blueprint, render_template , request, redirect, url_for, flash
from models.ModelUsuarios import Users
from utils.conexion import db
from flask_login import login_user, logout_user#, login_required

login = Blueprint('login', __name__)

@login.route('/')
@login.route('/index')
def index():
    return render_template('login.html')

@login.route('/logear', methods=['GET','POST'])
def logear():
    user = Users
    if request.method == 'POST':
        nickname = request.form['nickname']
        password = request.form['password']
        user = Users.query.filter_by(nickname=nickname).first()
        if user is not None and user.check_pw(password):
            login_user(user)
            print('usuario')
            return redirect(url_for('operations.welcomeUser'))
        else:
            flash('Usuario o password no valido!')
            return redirect(url_for('login.index'))
    else:
        return redirect(url_for('login.index'))

@login.route('/register')
def register():
    return render_template('register_user.html')

@login.route('/logout')
def salir():
    logout_user()
    return redirect(url_for('login.index'))

app/routes/routesOperations.py
from flask import Blueprint, render_template , request, redirect, url_for, flash
from models.ModelUsuarios import Users
from utils.conexion import db
from flask_login import  current_user, login_required
import random

operations = Blueprint('operations', __name__)

@operations.route('/welcomeUser')
@login_required
def welcomeUser():
    return render_template('home.html')

@operations.route('/exercise4')
@login_required
def exercise4():
    greetWM = []
    greetWW = []
    greetMW = []
    greetMM = []

    candidatesWoman = []
    candidatesMan = []

    mens = ['fernando', 'jose', 'martin', 'angel', 'jorge', 'tomas', 'francisco', 'omar','rodolfo', 'agustin', 'mario', 'ricardo', 'leonardo', 'vicente', 'luis', 'miguel', 'guillermo', 'javier', 'euduardo', 'alejandro', 'pedro', 'cesar', 'pablo', 'julian', 'jesus']
    womens = ['laura', 'edith', 'jimena', 'alejandra', 'barbara', 'arely', 'martha', 'teresa', 'maria', 'marina', 'miriam', 'samanta', 'lucia', 'leticia', 'linda', 'ana', 'liliana', 'elena','juliana', 'elisa', 'yolanada', 'raquel', 'gloria', 'selena', 'estefania']
    
    print('**Candidatos:')
    for i in range(1,7):
        woman = random.randint(0,24)
        man = random.randint(0,24)
        candidate = [womens[woman].capitalize(), mens[man].capitalize()]
        gender = random.randint(0,1)
        if gender == 0:  
            candidatesWoman.append(candidate[gender])
        else:
            candidatesMan.append(candidate[gender])
  
    print(' ')
    print('**Saludo: ')
    for i in candidatesWoman:

        for h in mens:
            greetWM.append(f'Estimado: {h.capitalize()}, soy la candidata: {i}')

        for m in womens:
            greetWW.append(f'Estimada: {m.capitalize()}, soy la candidata: {i}')

    for i in candidatesMan:
        for h in mens:
            greetMM.append(f'Estimado: {h.capitalize()}, soy el candidato: {i}')
        for m in womens:
            greetMW.append(f'Estimada: {m.capitalize()}, soy el candidato: {i}')

    return render_template('exercise4.html', name=current_user.name, 
    candidatesWoman = candidatesWoman, candidatesMan=candidatesMan,greetWM=greetWM, greetWW = greetWW,
    greetMM=greetMM, greetMW=greetMW )

@operations.route('/exercise5')
@login_required
def exercise5():
    mylist = []
    numMinors = []
    numGreater = []
    numSame = []
    numMultiples = []
    
    #My list
    for i in range(1,200):
        mynumber = random.randint(1,100)
        mylist.append(mynumber)
    mylist.sort()
  
    #Miniors
    for i in mylist:
        if mynumber <= i:
            break
        else:
            numMinors.append(i)
    long = len(numMinors)
    if long == 0:
        flash(f'No hay numero menores a {mynumber}')
    else:
        numMinors

    #Greater
    for i in mylist:
        if mynumber >= i:
            continue
        else:
            numGreater.append(i)
    long = len(numGreater)
    if long == 0:
        flash(f'No hay números mayores a {mynumber}')
    else:
        numGreater
    #Same
    for i in mylist:
        if mynumber == i:
            numSame.append(i)
        else:
            continue
    long = len(numSame)
    if long == 0:
        flash(f'No hay números iguales a{mynumber}')
        i = 'No hay números iguales'
        numSame.append(i)
    else:
        numSame
    #multiplos
    for i in mylist:
        if mynumber % i == 0:
            numMultiples.append(i)
        else:
            continue
    long = len(numMultiples)
    if long == 0:
        flash('No hay números iguales')
        i = 'No hay números iguales'
        numMultiples.append(i)
    else:
        numMultiples

    return render_template('exercise5.html', 
    name=current_user.name, mylist = mylist, mynumber=mynumber, numMinors=numMinors,
    numGreater=numGreater, numSame=numSame, numMultiples=numMultiples)


@operations.route('/register_user', methods=['POST'])
def register_user():
    try:
        name =request.form['name']
        name = name.capitalize()
        lastname = request.form['lastname']
        lastname =lastname.capitalize()
        nickname = request.form['nickname']
        len(nickname)
        while nickname.islower() == True  or nickname.isupper == True:
            flash("Nickname invalido, debe contener al menos una letra mayuscula y minuscula")
            return render_template('register_user.html')
        while nickname.isalpha() == True or nickname.isdigit() == True:
            flash("Nu nickname invalido, debe contener numeros y letras")
            return render_template('register_user.html')
        while len(nickname) < 6:
            flash("Nickname invalido, debe contener al menos 6 caracteres")
            return render_template('register_user.html')
        while nickname.isalpha() == True:
            flash("Nickname invalido, solo debe tener letras y numeros")
            return render_template('register_user.html')
        while nickname.isalnum() == False:
            flash("Nickname invalido, solo debe tener letras y numeros")
            return render_template('register_user.html')
        while nickname.find(" ") >= 1:
            return render_template('register_user.html')
        password = request.form['password']
        len(password)
        while password.islower() == True  or password.isupper == True:
            flash('su contraseña invalida, debe contener al menos una letra mayuscula y minuscula')
            return render_template('register_user.html')
        while password.isalpha() == True or password.isdigit() == True:
            flash("su contraseña invalida, debe contener numeros y letras")
            return render_template('register_user.html')
        while len(password) < 8:
            flash("su contraseña invalida, debe contener al menos 8 caracteres")
            return render_template('register_user.html')
        while password.isalpha() == True:
            flash("su contraseña invalida, debe tener letras y numeros")
            return render_template('register_user.html')
        while password.isalnum() == True:
            flash("su contraseña invalida, debe tener al menos un caracter no alfanumerico")
            return render_template('register_user.html')
        while password.find(" ") >= 1:
            flash("su contraseña invalida, no debe contener espacios")
            return render_template('register_user.html')        
        password2 = request.form['password2']
        while password != password2:
            flash("las contraseñas deben de ser iguales")
            return render_template('register_user.html')    
        user = Users.query.filter_by(nickname=nickname).first()
        if user:
            flash('usuario ya existe')
            return redirect(url_for('login.index'))
        new_user = Users(name =name, lastname=lastname, nickname=nickname, password=password)
        new_user.create_pw(password)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('login.index'))
    except Exception as e:
        db.session.rollback()
        db.session.close()
        print(f'error: {e}')
        return redirect(url_for('login.index'))



app/templates/exercise4.html
{% include 'layout.html' %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger alert-dismissible" role="alert">
    <strong>
        {{ message }}
    </strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>   
{% endfor %}
{% endif %}
{% endwith %}

<h3>Bienvenido: {{name}}</h3>

<div class="container-fluid" id="p2">
    <div class="row">

        <div class="text-left pt-3 col-sm-2" >
            <h5>Candidatas</h5>
            <br>
            {% for woman in candidatesWoman %}
                <li>
                    <h7>Soy la candidata: {{woman}}, vote por mi</h7>
                </li>
            {% endfor %}
            <br>
            <h5>Candidatos</h5>
            {% for man in candidatesMan %}
            <li>
                <h7>Soy el candidato: {{man}}, vote por mi</h7>
            </li>
            {% endfor %}
            <br>
        </div>

        <div class="col-sm-1">
            
        </div>
        
        <div class="text-left pt-3 col-sm-4">
            <h5>Votantes</h5>
            <br>
            {% for greetm in greetWM %}
                <li>
                    <h7>{{greetm}}</h7>
                </li>
            {% endfor %}

            {% for greetw in greetWW %}
                <li>
                    <h7>{{greetw}}</h7>
                </li>
            {% endfor %}
        </div>

        <div class="col-sm-1">
            
        </div>

        <div class="text-left pt-3 col-sm-4">
            <h5>Votantes</h5>
            <br>
            {% for greet in greetMM %}
                <li>
                    <h7>{{greet}}</h7>
                </li>
            {% endfor %}

            {% for greet in greetMW %}
                <li>
                    <h7>{{greet}}</h7>
                </li>
            {% endfor %}
        </div>

    </div>

</div>





app/templates/exercise5.html
{% include 'layout.html' %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger alert-dismissible" role="alert">
    <strong>
        {{ message }}
    </strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>   
{% endfor %}
{% endif %}
{% endwith %}

<h3>Bienvenido: {{name}}</h3>

<div class="container-fluid">
    <h5>Lista aleatoria, Número k: {{mynumber}}</h2>
    <div class="border border-2 border-danger text-left pt-3" id="p1">
        <p class="text-break">
            {% for num in mylist %}
                {{ num }}
            {% endfor %}
        </p>   
    </div>

    <br>

    <h5>Números menores a {{mynumber}}</h4>
    <div class="border border-2 border-danger text-left pt-3" id="p1">
        <p class="text-break">
            {% for num in numMinors %}
                {{ num }}
            {% endfor %}
        </p>
    </div>

    <br>

    <h5>Números mayores a {{mynumber}}</h4>
    <div class="border border-2 border-danger text-left pt-3" id="p1">
        <p class="text-break">
            {% for num in numGreater %}
                {{ num }}
            {% endfor %}
        </p>
    </div>

    <br>

    <h5>Números iguales a {{mynumber}}</h4>
    <div class="border border-2 border-danger text-left pt-3" id="p1">
        <p class="text-break">
            {% for num in numSame %}
                {{ num }}
            {% endfor %}
        </p>
    </div>

    <br>

    <h5>Números multiplos de {{mynumber}}</h4>
    <div class="border border-2 border-danger text-left pt-3" id="p1">
        <p class="text-break">
            {% for num in numMultiples %}
                {{ num }}
            {% endfor %}
        </p>
    </div>

    <br>
    <br>
   
</div>


app/templates/home.html
{% include 'layout.html' %}

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger alert-dismissible" role="alert">
    <strong>
        {{ message }}
    </strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>   
{% endfor %}
{% endif %}
{% endwith %}

<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    </div>

    <!--Image 1-->
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000"><a href="{{url_for('operations.exercise4')}}">
        <img src="{{url_for('static', filename='images/tuplas.jpg')}}" class="d-md-block w-100" alt="..." width="50%" height="100%"></a>
        <div class="carousel-caption d-none d-md-block">
          <h5>Exercise 4</h5>
          <p>Tupla de tuplas</p>
        </div>
      </div>

      <!--Image 2-->
      <div class="carousel-item" data-bs-interval="2000"><a href="{{url_for('operations.exercise5')}}">
        <img src="{{url_for('static', filename='images/listas.jpg')}}" class="d-md-block w-100" alt="..." width="50%" height="100%"></a>
        <div class="carousel-caption d-none d-md-block">
          <h5>Exercise 5</h5>
          <p>Lista de números</p>
        </div>
      </div>
    </div>

    <!--Controls-->
    <!--Button 1-->
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <!--Button 1-->
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>




app/templates/layout.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!DOCTYPE html>
<html lang="es-mx">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>app ORM</title>
    <link rel="shortcut icon" href="{{url_for('static', filename='images/iconopython.png')}}">
    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    
</head>
<body id="main">
    {% block body %}
    <div class="continer">
        <div class="continer">
            <nav class="navbar sticky-top navbar-light navbar-dark bg-dark" id="navegacion">
                <div class="container-fluid">
                    <!--Flask logo-->
                    <a href="{{url_for('operations.welcomeUser')}}">
                    <img src="{{ url_for('static', filename='images/flasklogo.png') }}" alt="" width="80" height="50" class="d-inline-block align-text-top"></a>
                  <form class="d-flex">
                    <a href="{{ url_for('login.salir') }}"><button type="button" class="btn btn-danger btn-sm">Logout</button></a>
                  </form>
                </div>
              </nav>
        </div>
    </div> 
    {% endblock %}
<!-- JS -->
<script type="text/javascript" src="{{url_for('static', filename='js/main.js' )}}"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

app/templates/layoutlogin.html
<!DOCTYPE html>
<html lang="es-mx">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>app ORM</title>
    <link rel="shortcut icon" href="{{url_for('static', filename='images/iconopython.png')}}">
    <!-- CDN Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
</head>
<body id="main">
    {% block body %}
    

    {% endblock %}
<!-- JS Bootstrap 5-->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

app/templates/login.html
{% include 'layoutlogin.html' %}

<div class="container text-center">
    <main class="form-signin">
        <form action="/logear" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <img class="mb-4" src="{{url_for('static', filename='images/python.png')}}" alt="" width="162" height="180">
            <!-- mensajes de alerta -->
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <strong>
                    {{ message }}
                </strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>   
            {% endfor %}
            {% endif %}
            {% endwith %}
            <h1 class="h3 mb-3 fw-normal">Login</h1>
            <div class="form-floating">
                <input type="text" class="form-control" id="floatingInput" name="nickname" placeholder="example-> user123" required>
                <label for="floatingInput">Nickname</label>
            </div>
            <div class="checkbox mb-3">
            
            </div>

            <div class="form-floating">
                <input type="text" class="form-control" id="floatingPassword" name="password" placeholder="Password" required>
                <label for="floatingPassword">Password</label>
            </div>
        
            <div class="checkbox mb-3">
            
            </div>

            <div class="form-floating">
                <button class="w-100 btn btn-lg btn-primary"type="submit">Iniciar Sesion</button>
            </div>

            <div class="checkbox mb-3">
            
            </div>

            <div class="form-floating">
                <a href="{{url_for('login.register')}}"><button type="button" class="w-100 btn btn-lg btn-success">Registrarse</button></a>
            </div>
            
            <p class="mt-5 mb-3 text-muted">&copy; 2022–2022</p>
      </form>
    </main>
</div>

app/templates/register_user.html
{% include 'layout.html' %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger alert-dismissible" role="alert">
    <strong>
        {{ message }}
    </strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>   
{% endfor %}
{% endif %}
{% endwith %}
    
<div class="container pt-5">
    <h1 class="text-center">Ingrese sus datos por favor</h1>
    <br>
    
    <form action="register_user"  method="POST" id="formulario">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="container pt-4">
    
            <div class="row"> 
                <div class="col-sm-6">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="addon-wrapping">Nombre</span>
                        <input id="name" type="text" name="name" class="form-control" placeholder="Ingrese el nombre" aria-label="name" aria-describedby="addon-wrapping" >
                    </div>
                </div>
    
                <div class="col-sm-6">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="addon-wrapping">Apellidos</span>
                        <input id="lastname" type="text" name="lastname" class="form-control" placeholder="Ingrese los apellidos" aria-label="lastname" aria-describedby="addon-wrapping">
                    </div>
                </div>
            </div>
       
                <div class="col-sm-12">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="addon-wrapping">Nickname</span>
                        <input id="nickname" type="text" name="nickname" class="form-control" placeholder="Ingrese el nickname (maximo 12 caracteres)" aria-label="nickname" aria-describedby="addon-wrapping">
                    </div>      
                </div>  

                <div class="col-sm-12">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="addon-wrapping">Password</span>
                        <input id="password" type="text" name="password" class="form-control" placeholder="Ingrese el password" aria-label="password" aria-describedby="addon-wrapping">
                    </div>      
                </div> 
                
                <div class="col-sm-12">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="addon-wrapping">Password</span>
                        <input id="password" type="text" name="password2" class="form-control" placeholder="Ingrese nuevamente password" aria-label="password" aria-describedby="addon-wrapping">
                    </div>      
                </div> 

                <div class="checkbox terms-checkbox">
                    <label>
                      <input type="checkbox" id="terms" id="checkbox" required> Acepto los términos y condiciones
                    </label>
                </div>
                <br>
                <div class="col-sm-1">
                    <div class="input-group mb-3">
                        <button type="submit" class="btn btn-success">Resgistrarse</button>
                    </div>
                </div> 
            </div>   
        </div>
    </form>
    

app/templates/registro.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Formulario de Registro</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div class="container">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Formulario de Registro</h1>
      <form>
        <div class="form-group">
          <label class="control-label" for="username">Usuario:</label>
          <input type="text" class="form-control input-lg" id="username" placeholder="Ingresa un usuario">
          <p class="help-block"></p>
        </div>
        <div class="form-group">
          <label class="control-label" for="password">Contraseña</label>
          <input type="password" class="form-control input-lg" id="password" placeholder="Ingresa una contraseña">
          <p class="help-block"></p>
        </div>
        <div class="checkbox terms-checkbox">
          <label>
            <input type="checkbox" id="terms"> Acepto los términos y condiciones
          </label>
        </div>
        <div class="action text-right">
          <button type="submit" class="btn btn-primary btn-block btn-lg">Registrarse</button>
        </div>
      </form>
    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="app.js"></script>
</body>
</html>

app/templates/update_user.html
{% include 'layout.html' %}

<div class="container pt-5">
    <h1 class="text-center">Actualizar mis datos</h1>
    <br>
    <form action="/update_user/{{user.id_user}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="container pt-4">
    
            <div class="row"> 
                <div class="col-sm-4">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="addon-wrapping">Nombre</span>
                        <input type="text" name="name" class="form-control" placeholder="Ingrese el nombre" aria-label="name" aria-describedby="addon-wrapping" value="{{user.name}}">
                    </div>
                </div>
    
                <div class="col-sm-8">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="addon-wrapping">Apellidos</span>
                        <input type="text" name="lastname" class="form-control" placeholder="Ingrese los apellidos" aria-label="lastname" aria-describedby="addon-wrapping" value="{{user.lastname}}">
                    </div>
                </div>
            </div>
    
                <div class="col-sm-10">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="addon-wrapping">Nickname</span>
                        <input type="text" name="nickname" class="form-control" placeholder="Ingrese el nickname" aria-label="nickname" aria-describedby="addon-wrapping" value="{{user.nickname}}">
                    </div>      
                </div>  
                
                <div class="col-sm-11">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="addon-wrapping">Password</span>
                        <input type="password" name="password" class="form-control" placeholder="Ingrese el password" aria-label="password" aria-describedby="addon-wrapping" value="{{user.password}}">
                    </div>      
                </div> 

                <div class="col-sm-1">
                    <div class="input-group mb-3">
                        <button type="submit" class="btn btn-success">Actualizar</button>
                    </div>
                </div> 
            </div>   
        </div>
    </form>
</div>